### ISSUE TITLE
How to ?

### ISSUE THREAD

**Issue by Olivcoq** [ivanokhotnikov/splines#1]
Hello,

I don't understand how lauch program?
Can you help me ?

Thanks

**Comment by ivanokhotnikov** [comment]
Hello,

Apologies for the late reply.
I've made some changes to README to include the usage examples.

The way to launch the program is to import the `Splines` class, then initialize the `Splines` instance with the string containing the splines spec and finally print the splines data with `print_drawing_data` method.

```
from splines import Splines

iso_splines = Splines('INT 25z x 1,0m x 30P x 5H - ISO 4156', None)
iso_splines.print_drawing_data()
```

Hope it helps.
Should you have any further questions, please let me know.

Kind regards,
Ivan
